name: Release Assets

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Set release tag
      id: vars
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
        else
          echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Checkout code at tag
      uses: actions/checkout@v4
      with:
        ref: refs/tags/${{ steps.vars.outputs.tag }}

    - name: Build artifacts
      run: |
        mkdir output
        echo "Built for tag ${{ steps.vars.outputs.tag }}" > output/info.txt

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

      # Copy USER_SECRETS.TEMPLATE.h to USER_SECRETS.h
    - name: Copy USER_SECRETS.TEMPLATE.h to USER_SECRETS.h
      run: cp ./Software/USER_SECRETS.TEMPLATE.h ./Software/USER_SECRETS.h

    - name: Build update image for Lilygo
      run: |
        pio run -e lilygo_330
        mkdir -p output
        mv .pio/build/lilygo_330/firmware.bin output/lilygo-update.bin

    - name: Build factory image for Lilygo
      run: |
        esptool --chip esp32 merge-bin -o .pio/build/lilygo_330/factory.bin --flash-mode dio --flash-freq 40m --flash-size 4MB 0x1000 .pio/build/lilygo_330/bootloader.bin 0x8000 .pio/build/lilygo_330/partitions.bin 0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 .pio/build/lilygo_330/firmware.bin
        mkdir -p output
        mv .pio/build/lilygo_330/factory.bin output/lilygo-factory.bin

    - name: Build update image for Stark
      run: |
        pio run -e stark_330
        mv .pio/build/stark_330/firmware.bin output/stark-update.bin

    - name: Build factory image for Stark
      run: |
        esptool --chip esp32 merge-bin -o .pio/build/stark_330/factory.bin --flash-mode dio --flash-freq 40m --flash-size 4MB 0x1000 .pio/build/stark_330/bootloader.bin 0x8000 .pio/build/stark_330/partitions.bin 0xe000 ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 .pio/build/stark_330/firmware.bin
        mkdir -p output
        mv .pio/build/stark_330/factory.bin output/stark-factory.bin

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.vars.outputs.tag }}
        files: |
          output/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
